spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.58.249.176:3306/sspaas?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: LAHMyyc@1233
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.pojo

CMS:
  USER_URL: http://v3cms.docker.sspaas.net/user/queryUser  #请求cms的user对象url
